### ISSUE TITLE
Should use shlex.split

### ISSUE THREAD

**Issue by Jwink3101** [cbartz/git-lfs-swift-transfer-agent#1]
I am not using this project but I am working on my own rclone-based transfer agent and this has been *super* helpful in making that (thanks) !

Anyway, you should use `shlex.split` instead of `<string>.split(' ')` to handle spaces and escapes. I can submit a pull-request but I do not have access to swift so I cannot test it.

**Comment by cbartz** [comment]
Thank you for your comment. Unfortunately, this project is no longer maintained.
